### ISSUE TITLE
Disable reset by button N seconds after boot.

### ISSUE THREAD

**Issue by Harvie** [mongoose-os-libs/provision#2]
Hello.
I need device to be reset if i hold the button for 10 seconds, but only if that happens in the first minute after boot. Can i make pull request providing such functionality?

```
  - ["provision.btn.hold_ms", "i", 10000, {title: "Hold interval in milliseconds. -1 to disable, 0 to reset if held on boot, > 0 to reset if held at runtime for this long."}]
  - ["provision.btn.inhibit_after_s", "i", 60, {title: "Disable reset button once uptime reaches this value in seconds. 0 to keep reset button always enabled."}]
```

**Comment by rojer** [comment]
makes sense, go ahead

**Comment by Harvie** [comment]
I've made the changes and tested on ESP32 device. (with both inhibition enabled and disabled).
Everything seems to work, pull request is at #3
