### ISSUE TITLE
Persisting config across config reset?

### ISSUE THREAD

**Issue by Harvie** [mongoose-os-libs/provision#6]
I know it might sound kinda weird, but i need to persist configuration across the reset (eg. `device.license`, which we provide separately when device becomes online for the first time).

How should i do it? Should i put it to `conf8.json`? Are there special uses for individual `confX.json` levels? i wasn't able to find reference for individual config levels.

**Comment by rojer** [comment]
config levels are described here: https://mongoose-os.com/docs/mongoose-os/userguide/configuration.md

**Comment by rojer** [comment]
there are no special rules for individual levels, except you should not use 0 (it's not even read anymore).
other than that, they are simply applied one after another, 1 to 9.

**Comment by Harvie** [comment]
Ok thanks. I was thinking that default config is generated to conf1.json or something, but then i realized the defaults are actualy compiled into build/gen/mgos_config.c

also`./deps/modules/mongoose-os/include/mgos_sys_config.h` gives me some insight:

```C
#define CONF_USER_FILE "conf9.json"

enum mgos_config_level {
  MGOS_CONFIG_LEVEL_DEFAULTS = 0,
  MGOS_CONFIG_LEVEL_VENDOR_1 = 1,
  MGOS_CONFIG_LEVEL_VENDOR_2 = 2,
  MGOS_CONFIG_LEVEL_VENDOR_3 = 3,
  MGOS_CONFIG_LEVEL_VENDOR_4 = 4,
  MGOS_CONFIG_LEVEL_VENDOR_5 = 5,
  MGOS_CONFIG_LEVEL_VENDOR_6 = 6,
  MGOS_CONFIG_LEVEL_VENDOR_7 = 7,
  MGOS_CONFIG_LEVEL_VENDOR_8 = 8,
  MGOS_CONFIG_LEVEL_USER = 9,
};
```
